"""Initial Migration

Revision ID: 0aeba4f59235
Revises: 
Create Date: 2020-05-31 12:27:50.749327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aeba4f59235'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('total_copy', sa.Integer(), nullable=True),
    sa.Column('issued_copy', sa.Integer(), nullable=True),
    sa.Column('present_copy', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('copy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.Column('issued_by', sa.Integer(), nullable=True),
    sa.Column('date_issued', sa.DateTime(), nullable=True),
    sa.Column('date_return', sa.DateTime(), nullable=True),
    sa.Column('book', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['book'], ['book.id'], ),
    sa.ForeignKeyConstraint(['issued_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('copy')
    op.drop_table('user')
    op.drop_table('book')
    # ### end Alembic commands ###
